### ISSUE TITLE
Put the camera in a separate thread to prevent buffering

### ISSUE THREAD

**Issue by Antonio217** [rr1706/vision2015#4]
A thought to prevent slow processing from buffering data.

http://www.chiefdelphi.com/forums/showthread.php?t=123390&highlight=OpenCV

**Comment by cmastudios** [comment]
I decided to thread the contours each instead (see e1a43e37aa8fe82c1cb195493c65f31f1901843c). It appeared that OpenCV must automatically thread the camera or something because buffering is not an issue like it was with V4L2.
