### ISSUE TITLE
Issues with building

### ISSUE THREAD

**Issue by 123dj** [rr1706/vision2015#6]
At first, I had quite a few issues when I tried to build this on a Raspberry Pi.  I built OpenCV from scratch, and now I'm getting different errors:
```
'map' was not declared in this scope (depth.cpp:161)
expected primary-expression before ',' token (depth.cpp:161)
expected primary-expression before '*' token (depth.cpp:161)
expected primary-expression before '>' token (depth.cpp:161)
'threads' was not declared in this scope (depth.cpp:161)
'Display_Game_Piece' was not declared in this scope (depth.cpp:187)
```

It seems a little strange that all the errors come from `depth.cpp`, and most of them are on line 161.  Any ideas on what's going wrong?

**Comment by cmastudios** [comment]
Hmm. For reference, what operating system/version are you using?
Try to add an
    #include <map>
at the beginning of the depth.cpp file. 
Thanks for your interest in our vision software!

**Comment by 123dj** [comment]
I'm running Raspbian 3.18.7.  Including `map` got rid of those errors, but introduced new ones:
```
robot.o: undefined reference to symbol '_ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorliSaliEE'
error adding symbols: DSO missing from command line (libopencv_imgcodecs.so.3.0)
collect2: error: ld returned 1 exit status
```
And none of the errors give a line number.  Do you think these errors are coming from trying to compile the code on a ARM processor?  What processor did you compile it on?  Thanks.

**Comment by faust1706** [comment]
The program runs on an ODroid XU, which has the Samsung Exynos5 Octa ARM Cortex.

Based off "libopencv_imgcodecs.so.3.0" I suspect your installation of opencv messed up somewhere.

**Comment by 123dj** [comment]
Okay... I'm using the latest dev beta build, 3.x.  Maybe it's a compatibility issue.  What version of OpenCV do you have, and did you install it through a package manager or compile yourselves?

**Comment by cmastudios** [comment]
I see. We have been using OpenCV 2.4.10 for the project. It works fine when installed through APT however the Xtion support is missing. I compiled it from source on the ODROID.

**Comment by 123dj** [comment]
Ugh.  Last time it took forever to compile 3.0 on the Pi, I'll probably have to compile 2.4 overnight.  I'll tell you the results tomorrow.

**Comment by 123dj** [comment]
It built with 2.4.10!   Moral of the story: always use the same version of a library as the authors.  Thanks for your help!
